### ISSUE TITLE
config option to render the prompt on one line (feature)

### ISSUE THREAD

**Issue by acidjazz** [frmendes/geometry#11]
Is there any particular reason the prompt always adds an extra line? I was wondering if we could add an option to remove that, I found if I changed

``` zsh
prompt_geometry_render() {
  PROMPT="
 %(?.$GEOMETRY_PROMPT.$GEOMETRY_EXIT_VALUE) %F{$GEOMETRY_COLOR_DIR}%3~%f "

  PROMPT2=" $GEOMETRY_SYMBOL_RPROMPT "
  RPROMPT="$(prompt_geometry_git_info)%{$reset_color%}"
}
```

to

``` zsh
prompt_geometry_render() {
  PROMPT="%(?.$GEOMETRY_PROMPT.$GEOMETRY_EXIT_VALUE) %F{$GEOMETRY_COLOR_DIR}%3~%f "
  PROMPT2=" $GEOMETRY_SYMBOL_RPROMPT "
  RPROMPT="$(prompt_geometry_git_info)%{$reset_color%}"
}
```

and i get a single line 

![image](https://cloud.githubusercontent.com/assets/967369/18122453/7acb1980-6f1e-11e6-951d-f7235c3bd599.png)

unless you think this would break anything I'm happy to submit a PR w/ this as a feature/optoin

**Comment by frm** [comment]
When I first made this I was just hacking away at another theme. I only open sourced it later, so even though I refactored out most of the code, there are still some bits that are there purely because of aesthetic preference.

If you can refactor that into a config variable like the rest of the theme it would be great! And if you find other options that you think you would prefer to customize, feel free to extract it out to a variable and submit a PR! I'd really appreciate it.

**Comment by acidjazz** [comment]
You got it!

**Comment by frm** [comment]
Are you up for submiting a PR with this option?

**Comment by acidjazz** [comment]
@frmendes yes, apologies, as soon as i catch a break, sometime this week.

**Comment by frm** [comment]
@acidjazz, no worries, happens to everyone! Feel free to take your time. Just checking in order to clean up the issues.

**Comment by desyncr** [comment]
ping @acidjazz Are you still interested?

**Comment by acidjazz** [comment]
thanks @desyncr for taking care of this, sorry i couldn't make the time to do so!
