### ISSUE TITLE
Async library tries to erase temporal files from other users

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#114]
[Async lib](https://github.com/frmendes/geometry/blob/master/lib/async.zsh) uses temporal files to communicate with background jobs.

When a new prompt is loaded the function `geometry_async_setup` tries to clean up -possibly- stalled temporal files. In doing so it does not check the ownership (ex, a prompt for `root`). So it may face a prompt to confirm deletion (`zsh 5.3`).

A possible solution is to use `$UID` to [prefix temporal files](https://github.com/frmendes/geometry/blob/master/lib/async.zsh#L3):

    typeset -g GEOMETRY_ASYNC_TMP_FILENAME_PREFIX='.geometry-rprompt-info-'$UID'-'

**Comment by frm** [comment]
`$UID` is a great option IMO.

**Comment by thomasdesr** [comment]
So I hit this today when trying out geometry for the first time. 

After debugging for a bit I ended up with a slightly different solution which was to both make the `rm` forceful and add a graceful exit hook to clean up of the temp file.

```diff
diff --git a/lib/async.zsh b/lib/async.zsh
index 01d4d68..5e1134f 100644
--- a/lib/async.zsh
+++ b/lib/async.zsh
@@ -23,12 +23,18 @@ typeset -g GEOMETRY_ASYNC_PROC_ID=0
     GEOMETRY_ASYNC_PROC_ID=$!
 }

+# Clean up the async temp file when zsh exits
+-geometry_async_zshexit() {
+    rm -f "${GEOMETRY_ASYNC_TMP_FULL_PATH}$$"
+}
+
 # Hooks precmd to run `-geometry_async_function` and hooks
 # `USR1` signal to comunicate with it
 geometry_async_setup() {
     add-zsh-hook precmd '-geometry_async_precmd'

-    (\rm ${GEOMETRY_ASYNC_TMP_FULL_PATH}*) &> /dev/null
+    add-zsh-hook zshexit '-geometry_async_zshexit'
+    \rm -f ${GEOMETRY_ASYNC_TMP_FULL_PATH}* &> /dev/null

     TRAPUSR1() {
         # read from temp file
```

I ran into particular difficulty debugging the hang after enabling trace because the `rm` was being run in a subshell. So I removed that as well.

I'd be happy to open a PR that uses some combination of the proposed options to resolve this issue but would like some advice on which of the above to implement. I'm currently using the forceful rm + hook locally and it seems to be working out.

**Comment by desyncr** [comment]
I like the idea of `zshexit` hook, if it works then let's use it. We can even get rid of `rm` in `geometry_async_setup`!

Let's go for it! @thomaso-mirodin

**Comment by frm** [comment]
Oooh, this is nice. Nice solution. By looking at the diff, and this is me getting ahead of code review, if you see yourself using `\rm -f ${GEOMETRY_ASYNC_TMP_FULL_PATH}* &> /dev/null` more than once, consider extracting it to a separate function.

All in all, this is nice, open up a PR.
