### ISSUE TITLE
Virtualenv support

### ISSUE THREAD

**Issue by LuRsT** [frmendes/geometry#18]
Hi @frmendes, I found this theme recently and am loving it, but it's missing Python's virtualenv support, if I send a PR, are you interested in merging such a feature?

**Comment by frm** [comment]
Hi!

Yes, I would. Just make sure you disable it by default since this isn't a feature that all users want enabled. You can provide an option, through an environment variable, to enable it. Similar to what [the remaining customizable options](https://github.com/frmendes/geometry/blob/master/geometry.zsh#L48-L51) do.

**Comment by LuRsT** [comment]
Cool, sounds sensible, expect my PR :D!
