### ISSUE TITLE
Consider switch to zstyle from env

### ISSUE THREAD

**Issue by jedahan** [frmendes/geometry#219]
Upsides
+ less env pollution
+ easier to query
+ more zsh-y
+ export order no longer matters?

Downsides
- harder to port to other shells
- harder to learn
- unknown issues

Example of how it may work inspired by [zsh-prompt-newt](https://github.com/softmoth/zsh-prompt-newt#segments)

```zsh
zstyle :prompt:geometry:prompt:primary path hostname
zstyle :prompt:geometry:prompt:secondary exec_time todo git rustup +hydrate
```

```zsh
zstyle :prompt:geometry:plugin:hydrate bindkey '^L'
zstyle :prompt:geometry:plugin:hydrate color blue
```

**Comment by frm** [comment]
I like the idea to go deep into zsh and use modules.

It would make it harder on #209 but I've been giving it some thought and I'd rather close that for now. It makes sense to go the Unix-way: focus on zsh and do it well. If we consider porting to fish, then we should do fish well. Not a hybrid between both.

The unknown issues worry me especially because we have no tests. So, here's my suggestion: stabilize geometry (finish with the themes, update some outdated READMEs, etc), make a release, update the README to point to the release tag when installing. Start porting to `zstyle` and iterate over bugs that arise.

How do you feel about this?

**Comment by jedahan** [comment]
I've changed my mind on this since the benefits are so minor and the downsides are not.
