### ISSUE TITLE
Add section with user submitted plugins

### ISSUE THREAD

**Issue by desyncr** [frmendes/geometry#97]
To give visibility and kick start a plugin ecosystem.

Meanwhile most custom plugins are rather too specific for publishing there is still a place for plugins for 'svn', for example.

Thoughts you guys?

**Comment by frm** [comment]
I only half agree on this. I'm ok with most of the tooling or language specific plugins as these cater to most users needs. Some like `hg` or `exec_time` could be extract to a custom section. It has to be on a case-by-case basis but if we are doing this, we should consider defining some criteria.

**Comment by desyncr** [comment]
I think the criteria should be quite simple:

a) Is the target tooling current? (ie, wide use, think git vs svn)
b) Information shown is targeted towards a wide audience? (ie, useful for the common user)

For example, [this one](https://github.com/desyncr/geometry-pretty-git) should be left out as it doesn't match point b). While [this other one](https://github.com/desyncr/geometry-dir-info-prompt) could be included as a custom plugin.

**Comment by jedahan** [comment]
It costs very little to keep files in the main tree for now. I would not like to see geometry start to grow it's own package manager which is the road I see this going down. Until there are plugin conflicts or unmaintained packages, frmendes has been great at merging and responding to pull requests.

**Comment by jedahan** [comment]
Us deciding what a wide audience is tricky - it feels good to have your patch committed upstream and increases the use of the prompt as it is easier to install and use

**Comment by desyncr** [comment]
My concern is to end up with a huge number of rare and/or unused plugins because once it's merged into geometry we're then responsible for it's maintenance.

We should be able to draw the line on which plugin we want to maintain.

**Comment by frm** [comment]
I agree with @jedahan when he says it's not that costly. I see more advantages in allowing most plugins as it increases user interaction and contribution, it's easier for users and a great byproduct (which has actually motivated me to step down a bit from responding to issues) is that there have been quite a few new contributors to open source through geometry.

After giving this a thought, I got a bit scared that having strict criteria and pushing plugins to a "User Plugins" section might put some barriers to that. People might think twice before contributing while I'd rather have a PR and give out feedback. If it turns out the plugin is really not that necessary, it's all good. Just correct the PR to add it to a README.

However, I also agree that [this plugin](https://github.com/desyncr/geometry-pretty-git) is simply a great demonstration of sense of humor, not to be merged, and I would very much be ok with having it in a "User Plugins" section. I think I'd rather go with that and be a lot more lenient with user contributions. Accept most plugins and praise "outstanding" custom user plugins -- say if someone decides to turn geometry into all emojis -- by adding them to a public list.

Finally, I share @desyncr 's concern for unused plugin maintenance. I don't have a clear idea on what is the best option for that but I'm a bit more concerned about raising barriers to contributions than unused plugin maintenance. I'm all up for suggestions on this and would very much appreciate constructive feedback.

What do you both think?

PS:

> I would not like to see geometry start to grow it's own package manager which is the road I see this going down.

I don't want to detach geometry from existing tooling and I don't want it to become its own package manager. The way I see it is that it's transforming into a tool for prompt building with sane defaults and easy customization -- the plugins. I actually think that this transformation is positive. With just a couple of lines I can completely change the look of my terminal without bringing in extra dependencies.

**Comment by jedahan** [comment]
@desyncr when you say add section, where do you mean to add it?

If it is in the readme or a wiki page (or both), I think that is a great idea for people to quickly share cool stuff they have made (like any of the awesome- lists).

I think it would also be nice to add to the readme a quick 'howto use third-party geometry plugins' (clone it/zplug it somewhere, and source after geometry.zsh).

I do want to encourage users to submit their cool plugins to the main project - right now that number is small and we can take it on a case-by-case basis. Its good to think about what the maintenance cost is, but I still think its better to generally encourage open source contributions on the whole.

**Comment by desyncr** [comment]
I meant a README.md. A wiki page would be better off now that I think about it.

> I think it would also be nice to add to the readme a quick 'howto use third-party geometry plugins' (clone it/zplug it somewhere, and source after geometry.zsh).

This is a good idea.

**Comment by jedahan** [comment]
Something like https://github.com/jedahan/geometry/wiki/Plugins , which we can link in the readme perhaps

**Comment by desyncr** [comment]
Yep, sounds good to me!

**Comment by frm** [comment]
I guess we're all on the page. Any of you want to take this or should I?

**Comment by jedahan** [comment]
Its weird, every time I go to https://github.com/frmendes/geometry/wiki it just redirects to https://github.com/frmendes/geometry ...

**Comment by desyncr** [comment]
@jedahan It's because it didn't existed when you visited it. I just created the main page, now you should be able to create further sections.

**Comment by jedahan** [comment]
@desyncr mind sharing edit permissions?

**Comment by frm** [comment]
@jedahan just added you as a collaborator. You should have edit permissions once you accept it.

**Comment by desyncr** [comment]
@jedahan Welcome aboard!

**Comment by desyncr** [comment]
Well, it's done https://github.com/frmendes/geometry/wiki/Plugins. Thanks @jedahan 

I'm gonna update the page with new screenshots and probably another custom plugin.
